### ISSUE TITLE
Issue with processing the fragmented data

### ISSUE THREAD

**Issue by AlexeyKasatkin** [Mirantis/k8s-netchecker-agent#20]
Sometimes keepalive length from agents exceeds possible packet length for the network and server cannot decode the packets. E.g.:
http://paste.openstack.org/show/609357/
"zeroextenderlength" is set to 1500 by default which is too big.
Please consider reducing default value for this variable.

**Comment by AlexeyKasatkin** [comment]
Variable description "Length of zero bytes extender array that will be added to the agent's payload in case its size is less than MTU value. Is used to reveal problems with network packets fragmentation." seems to be inaccurate as MTU is not considered anywhere in the code.

**Comment by adidenko** [comment]
>  Please consider reducing default value for this variable.

No way. Extender was added exactly for this reason - to test payload. Please fix the server part, but do not reduce zeroextender.

**Comment by AlexeyKasatkin** [comment]
`E0511 10:29:47.986438       1 utils.go:87] Failed to process the request's data. Error while unmarshaling data. Details: invalid character '\x00' looking for beginning of value [negroni] 2017-05-11T10:29:47Z | 500 |   176.254µs | netchecker-service:8081 | POST /api/v1/agents/netchecker-agent-hostnet-h4sp6`

**Comment by AlexeyKasatkin** [comment]
Agree. It seems to be an issue with parameters on sender/receiver side.
